export const wineProducts = [
  {
    id: 1,
    title: "Wine 1",
    img: "https://images.unsplash.com/photo-1545608508-78f351665a1c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2734&q=80",
    price: "",
    region: "ITALIA, PUGLIA",
    info: "Information about wine.  Name of wine.  What region. Tasting Notes. Additional information",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Wine 2",
    img: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80",
    price: "",
    region: "FRANCE, BORDEAUX",
    info: "Information about wine.  Name of wine.  What region. Tasting Notes. Additional information",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Wine 3",
    img: "https://images.unsplash.com/photo-1474722883778-792e7990302f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2768&q=80",
    price: "",
    region: "ESPAÑA, BARCELONA",
    info: "Information about wine.  Name of wine.  What region. Tasting Notes. Additional information",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Wine 4",
    img: "https://images.unsplash.com/photo-1547595628-c61a29f496f0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80",
    price: "",
    region: "ARGENTINA, MENDOZA",
    info: "Information about wine.  Name of wine.  What region. Tasting Notes. Additional information",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Wine 5",
    img: "https://images.unsplash.com/photo-1553682544-4ccf2778c9a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80",
    price: "",
    region: "ITALIA, MILANO",
    info: "Information about wine.  Name of wine.  What region. Tasting Notes. Additional information",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Wine 6",
    img: "https://images.unsplash.com/photo-1566452281814-fb749694b25d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=668&q=80",
    price: "",
    region: "ESPAÑA, VALENCIA",
    info: "Information about wine.  Name of wine.  What region. Tasting Notes. Additional information",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Wine 7",
    img: "https://images.unsplash.com/photo-1590252223785-52831849d263?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=670&q=80",
    price: "",
    region: "ESPAÑA, VALENCIA",
    info: "Information about wine.  Name of wine.  What region. Tasting Notes. Additional information",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Wine 8",
    img: "https://images.unsplash.com/photo-1586636539865-52064fb82ba3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=668&q=80",
    price: "",
    region: "FRANCE, BORDEAUX",
    info: "Information about wine.  Name of wine.  What region. Tasting Notes. Additional information",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Wine 9",
    img: "https://images.unsplash.com/photo-1474722883778-792e7990302f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2768&q=80",
    price: "",
    region: "ESPAÑA, BARCELONA",
    info: "Information about wine.  Name of wine.  What region. Tasting Notes. Additional information",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "WINE DETAILS 1",
  img: "",
  region: "NEW ZEALAND, MARLBOROUGH",
  price: 28,
  info: "A very detailed account of the wine.",
  inCart: false,
  count: 0,
  total: 0,
};
