export const wineProducts = [
  {
    id: 1,
    year: 2015,
    title: "Rasteau",
    img: "https://images.unsplash.com/photo-1545608508-78f351665a1c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2734&q=80",
    price: 57,
    region: "Southern Rhone, France",
    info: "The Southern Rhône is situated in a large, sprawling valley, shaped by the course of the Rhône River. A Mediterranean climate makes the Southern Rhône Valley one of the warmest wine growing regions in France. Grape varieties that thrive in the region are well-suited to the hot, humid summers, and Grenache, Syrah, and Mourvèdre are by far the most common plantings.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    year: 2016,
    title: "Château de Pressac",
    img: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80",
    price: 64,
    region: "France, Bordeaux",
    info: "There exists in Bordeaux a small set of wines that sit just outside the limelight captured by the famous First Growths, but offer everything you could possibly want in a red wine at an unbelievable price.The 2016 Château de Pressac is one such brilliant Bordeaux. An under-the-radar picture of Right Bank opulence, Vinous’ Antonio Galloni has called the Grand Cru Classé Château Pressac “one of Bordeaux’s most unique and intriguing wines,” and he named the 2016 “one of the sleepers of Saint-Émilion.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Bordón Gran Reserva",
    year: 2011,
    img: "https://images.unsplash.com/photo-1474722883778-792e7990302f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2768&q=80",
    price: 110,
    region: "España, Rioja",
    info: "Central to the Spanish winemaking philosophy is the belief that wine should be released only when it is ready to be consumed, and not a moment before. Spanish wine law focuses squarely on this issue: the terms Crianza, Reserva and Gran Reserva are highly regulated indicators of the amount of time a wine has aged prior to its release. In Rioja, Navarra, and the Ribera del Duero (which have the most stringent requirements) red Crianzas must be aged a minimum of two years; Reservas, at least three years; and Gran Reservas, five years. Of course, top producers will often age their wines far longer than they are required to - sometimes decades.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Domaines Ott Clos Mireille",
    year: 2019,
    img: "https://images.unsplash.com/photo-1547595628-c61a29f496f0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80",
    price: 70,
    region: "France, Côtes de Provence",
    info: "More than just a European vacation hotspot and rosé capital of the world, Provence, in southeastern France, is a coastal appellation producing interesting wines of all colors. The warm, breezy Mediterranean climate is ideal for grape growing and the diverse terrain and soil types allow for a variety of wine styles within the region. Adjacent to the Rhône Valley, Provence shares some characteristics with this northwestern neighbor—namely, the fierce mistral wind and the plentiful wild herbs (such as rosemary, lavender, juniper and thyme) often referred to as garrigue. The largest appellation here is Côtes de Provence, followed by Coteaux d’Aix-en-Provence.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Cloudy Bay Te Koko Sauvignon Blanc",
    year: 2016,
    img: "https://images.unsplash.com/photo-1553682544-4ccf2778c9a8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80",
    price: 70,
    region: " Marlborough, New Zealand",
    info: "Aromatic on the nose, with notes of white peach, preserved citrus and a hint of topicality. The palate is expressive and vibrant, with a balance between ripe stone fruits and citrus intensity. With time in the glass, the wine opens out to reveal appealing guava and rambutan characters, alongside some more honeyed characters. Concentrated and complex, the wine finishes long, with lingering notes of orchard fruit and a pleasing burst of freshness.",
    inCart: false,
    count: 0,
    total: 0, 
  },
  {
    id: 6,
    title: "Bodegas Vega Sicilia Valbuena 5",
    year: 2015,
    img: "https://images.unsplash.com/photo-1602800268804-4a850d622360?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80",
    price: 205,
    region: "Ribera del Duero, Spain",
    info: "Valbuena, is the purest expression of the Tinto Fino (Tempranillo) in Vega Sicilia. Tinto Fino is clearly the predominant wine in the assemblage of the varieties that make up this magnificent wine. The other variety used is Merlot, which is added to a greater or lesser extent depending on the vintage. Valbuena 5º 2015 is a concentrated and powerful vintage, but at the same time silky and deep.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Chateau de Fargues Sauternes Blend",
    year: 1996,
    img: "https://images.unsplash.com/photo-1590252223785-52831849d263?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=670&q=80",
    price: 90,
    region: "France, Bordeaux, Sauternes",
    info: "Chateau de Fargues is one of the oldest estates in the Sauternes appellation of Bordeaux and has been in the Lur Saluces family since 1472. Wine production only began in the 19th century, and not until 1935 were white grapes planted.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Ornellaia, Bordeaux Red Blend",
    year: 2017,
    img: "https://images.unsplash.com/photo-1586636539865-52064fb82ba3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=668&q=80",
    price: 220,
    region: "Bolgheri, Tuscany, Italy",
    info: "The Ornellaia 2017 masterfully interprets what was a particularly warm and sunny year. The intense and dark color heralds a wine of beautiful concentration; the nose, rich and complex, releases scents of ripe red fruits, accompanied by notes of sweet tobacco and vanilla. The taste reveals an Ornellaia of great balance, a combination of firmness and pleasant freshness.Blend: 56% Cabernet Sauvignon, 25% Merlot, 10% Petit Verdot, 9% Cabernet Franc",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Bisol Cartizze Prosecco Superiore",
    year: 2019,
    img: "https://images.unsplash.com/photo-1560512823-829485b8bf24?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80",
    price: 50,
    region: "Valdobbiadene, Prosecco, Italy",
    info: "Flat-out gorgeous from start to finish, the 2019 Valdobbiadene Superiore di Cartizze mixes power and ripeness with stimulating acids and a soothing bead of fine bubbles to create a wonderful balanced expression. Yellow florals, ripe apple, musky pear and sweet spices make for an alluring display. It’s crisp and juicy, offset by an inner sweetness that’s impossible to ignore; yet it completes the expression perfectly. This is listed as dry, yet there’s about 25 grams per liter of residual sugar here. That said, it frames the expression perfectly to create a highly pleasurable Cartizze Prosecco.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Rutini Apartado Gran Malbec",
  year: "2015",
  img: "https://images.unsplash.com/photo-1577471486579-ea9de38e06fe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=654&q=80",
  region: "Malbec from Mendoza, Argentina",
  price: 99,
  info: "Intense red, with violet hues. On the nose, notes of very ripe red fruits appear accompanied by others of bitter cocoa and tobacco, which gives it contact with the oak. In the mouth, it is a wine of great structure, with a persistent finish, and smooth tannins. In the complexity of this wine the harmony achieved between the oak and the intense fruity frame is appreciated. Blend: 40% Malbec de Gualtallary, 40% Malbec de Altamira, 20% Malbec de La Consulta.",
  acclaim: "Critical Acclaim 96 Points - James Suckling This is a great malbec that shows richness and freshness with fresh herbs and a stem character. Medium body, fine tannins and a juicy finish. Wet earth, too. A malbec that transcends the grape and persists with complexity and beauty.",
  specs: "750ML / 14.5% ABV",
  inCart: false,
  count: 0,
  total: 0,
};
